// Technical line-drawing diagram used on the hero and division/service headers.
// Matches the SVG generated by the design's `diag(top, bottom)` helper.
import { t, type Lang } from '@/content/i18n';

export function TechDiagram({ top, bottom }: { top: string; bottom: string }) {
  return (
    <div className="border border-line2 rounded-[14px] bg-paper p-6">
      <div className="flex justify-between mono text-[10px] tracking-[0.12em] text-muted mb-3">
        <span>{top}</span>
        <span>N.T.S.</span>
      </div>
      <svg viewBox="0 0 360 220" width="100%" role="img" aria-label="Technical diagram" className="block">
        <rect x="8" y="8" width="344" height="204" fill="none" stroke="var(--line2)" strokeWidth="1" />
        <g stroke="var(--ink)" strokeWidth="1.3" fill="oklch(0.93 0.012 230 / .45)">
          <rect x="24" y="24" width="150" height="80" />
          <rect x="186" y="24" width="150" height="80" />
          <rect x="24" y="116" width="312" height="80" />
        </g>
        <g stroke="var(--accent-ink)" strokeWidth="1.5" opacity="0.55" fill="none">
          <path d="M40 30 L110 92" />
          <path d="M60 30 L120 78" />
        </g>
        <g stroke="var(--muted)" strokeWidth="0.7" strokeDasharray="3 3">
          <path d="M24 206 L336 206" />
          <path d="M24 210 L24 200" />
          <path d="M336 210 L336 200" />
        </g>
        <text x="180" y="204" fontFamily="var(--font-mono)" fontSize="8.5" fill="var(--muted)" textAnchor="middle">
          {bottom}
        </text>
      </svg>
    </div>
  );
}

/** The larger elevation on the home hero (curtain wall). */
export function CurtainWallElevation({ lang }: { lang: Lang }) {
  const d = t(lang);
  return (
    <div
      className="relative border border-line2 rounded-2xl bg-paper p-[22px]"
      style={{ boxShadow: '0 30px 70px -40px oklch(0.2 0.02 255/.4)' }}
    >
      <div className="flex justify-between mono text-[10.5px] tracking-[0.14em] text-muted mb-[14px]">
        <span>{d.elevationLabel}</span>
        <span>{d.scaleNts}</span>
      </div>
      <svg
        viewBox="0 0 400 300"
        width="100%"
        role="img"
        aria-label={
          lang === 'ar'
            ? 'رسم مسقط رأسي لنظام حائط ساتر من الألمنيوم'
            : 'Technical elevation drawing of an aluminium curtain-wall system'
        }
        className="block"
      >
        <defs>
          <linearGradient id="gl-home" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0" stopColor="oklch(0.91 0.012 230)" stopOpacity="0.5" />
            <stop offset="1" stopColor="oklch(0.97 0.006 230)" stopOpacity="0.15" />
          </linearGradient>
        </defs>
        <rect x="10" y="10" width="380" height="280" fill="none" stroke="var(--line2)" strokeWidth="1" />
        <g fill="url(#gl-home)" stroke="var(--ink)" strokeWidth="1.4">
          <rect x="24" y="24" width="108" height="112" />
          <rect x="146" y="24" width="108" height="112" />
          <rect x="268" y="24" width="108" height="112" />
          <rect x="24" y="150" width="108" height="126" />
          <rect x="146" y="150" width="108" height="126" />
          <rect x="268" y="150" width="108" height="126" />
        </g>
        <g stroke="var(--accent-ink)" strokeWidth="1.6" opacity="0.6">
          <path d="M40 30 L112 118" fill="none" />
          <path d="M60 30 L120 100" fill="none" />
          <path d="M284 156 L356 260" fill="none" />
        </g>
        <g stroke="var(--muted)" strokeWidth="0.8" strokeDasharray="3 3">
          <path d="M24 300 L24 286" />
          <path d="M376 300 L376 286" />
          <path d="M10 300 L376 300" />
        </g>
        <text x="193" y="296" fontFamily="var(--font-mono)" fontSize="9" fill="var(--muted)" textAnchor="middle">
          {lang === 'ar' ? 'تباعد القوائم' : 'MULLION SPACING'}
        </text>
      </svg>
      <div className="grid grid-cols-2 gap-2 mt-4">
        <div className="border border-line rounded-[9px] px-[13px] py-[11px]">
          <div className="mono text-[10px] text-muted tracking-[0.1em]">{d.glazing}</div>
          <div className="font-semibold text-[14px]">{d.glazingValue}</div>
        </div>
        <div className="border border-line rounded-[9px] px-[13px] py-[11px]">
          <div className="mono text-[10px] text-muted tracking-[0.1em]">{d.frame}</div>
          <div className="font-semibold text-[14px]">{d.frameValue}</div>
        </div>
      </div>
    </div>
  );
}
